Black-ed setup.py and added .DS_Store to gitignore
patdaburu/cookiecutter-click pull request #173
Opened 2021-06-10 17:29 UTC by lockefox

Updated setup.py to play nice with black https://github.com/psf/black

Highly suggest adding black to the make lint steps as well

2021-06-11 12:52 UTC, patdaburu approved these changes
These changes look good to me.

2021-06-14 10:10 UTC, vladdoster commented on {{cookiecutter.project_name}}/.gitignore
> +
Please add

```
# VS Code settings
.vscode
```

2021-06-14 10:12 UTC, vladdoster requested changes
Please see my comment. Thank you! 🚀

2021-06-14 20:43 UTC, lockefox commented
added requested vscode block to .gitignore

2021-06-19 02:45 UTC, vladdoster approved these changes
Awesome work @lockefox ! I am a big fan of black!

2021-06-19 02:47 UTC, merged